# Generated by Django 4.1.3 on 2022-11-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sponsoraplication_spent_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsoraplication',
            name='spent_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
